#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from pract5.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 2 "pract5.y"

	/*Definition Section*/
	#include <stdio.h>
	#include <string.h>
	#include <stdlib.h>

	//Structure to hold symbol table entry
	typedef struct variable{
		char name[63];
		char type[63];
		int value;
		struct variable *next;
	}variable;

	//Array of Symbol Entries
	variable *symbolTable[1000];

	int hashCalc(unsigned char *str);
	int insert(char* name, char* type);
	variable* search(char* input);
	void display();
	void freeTable();
	void init();
	int flag=0;

#line 28 "pract5.y"
typedef union 
{
	int i;
	float f;
	char c;
	char *string;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	INT	258
#define	FLOAT	259
#define	CHAR	260
#define	DOUBLE	261
#define	SEMICOLON	262
#define	COMMA	263
#define	END	264
#define	EQUAL	265
#define	PLUS	266
#define	MINUS	267
#define	MUL	268
#define	DIV	269
#define	LEFT	270
#define	RIGHT	271
#define	IF	272
#define	ELSE	273
#define	FOR	274
#define	WHILE	275
#define	DO	276
#define	LESS	277
#define	GREATER	278
#define	NOT	279
#define	AND	280
#define	OR	281
#define	CL	282
#define	CR	283
#define	LESSEQ	284
#define	GREATEREQ	285
#define	EQEQ	286
#define	NOTEQ	287
#define	ID	288
#define	INT_VAL	289
#define	FLOAT_VAL	290
#define	CHAR_VAL	291


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int INT;
static const int FLOAT;
static const int CHAR;
static const int DOUBLE;
static const int SEMICOLON;
static const int COMMA;
static const int END;
static const int EQUAL;
static const int PLUS;
static const int MINUS;
static const int MUL;
static const int DIV;
static const int LEFT;
static const int RIGHT;
static const int IF;
static const int ELSE;
static const int FOR;
static const int WHILE;
static const int DO;
static const int LESS;
static const int GREATER;
static const int NOT;
static const int AND;
static const int OR;
static const int CL;
static const int CR;
static const int LESSEQ;
static const int GREATEREQ;
static const int EQEQ;
static const int NOTEQ;
static const int ID;
static const int INT_VAL;
static const int FLOAT_VAL;
static const int CHAR_VAL;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,INT=258
	,FLOAT=259
	,CHAR=260
	,DOUBLE=261
	,SEMICOLON=262
	,COMMA=263
	,END=264
	,EQUAL=265
	,PLUS=266
	,MINUS=267
	,MUL=268
	,DIV=269
	,LEFT=270
	,RIGHT=271
	,IF=272
	,ELSE=273
	,FOR=274
	,WHILE=275
	,DO=276
	,LESS=277
	,GREATER=278
	,NOT=279
	,AND=280
	,OR=281
	,CL=282
	,CR=283
	,LESSEQ=284
	,GREATEREQ=285
	,EQEQ=286
	,NOTEQ=287
	,ID=288
	,INT_VAL=289
	,FLOAT_VAL=290
	,CHAR_VAL=291


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::INT=258;
const int YY_parse_CLASS::FLOAT=259;
const int YY_parse_CLASS::CHAR=260;
const int YY_parse_CLASS::DOUBLE=261;
const int YY_parse_CLASS::SEMICOLON=262;
const int YY_parse_CLASS::COMMA=263;
const int YY_parse_CLASS::END=264;
const int YY_parse_CLASS::EQUAL=265;
const int YY_parse_CLASS::PLUS=266;
const int YY_parse_CLASS::MINUS=267;
const int YY_parse_CLASS::MUL=268;
const int YY_parse_CLASS::DIV=269;
const int YY_parse_CLASS::LEFT=270;
const int YY_parse_CLASS::RIGHT=271;
const int YY_parse_CLASS::IF=272;
const int YY_parse_CLASS::ELSE=273;
const int YY_parse_CLASS::FOR=274;
const int YY_parse_CLASS::WHILE=275;
const int YY_parse_CLASS::DO=276;
const int YY_parse_CLASS::LESS=277;
const int YY_parse_CLASS::GREATER=278;
const int YY_parse_CLASS::NOT=279;
const int YY_parse_CLASS::AND=280;
const int YY_parse_CLASS::OR=281;
const int YY_parse_CLASS::CL=282;
const int YY_parse_CLASS::CR=283;
const int YY_parse_CLASS::LESSEQ=284;
const int YY_parse_CLASS::GREATEREQ=285;
const int YY_parse_CLASS::EQEQ=286;
const int YY_parse_CLASS::NOTEQ=287;
const int YY_parse_CLASS::ID=288;
const int YY_parse_CLASS::INT_VAL=289;
const int YY_parse_CLASS::FLOAT_VAL=290;
const int YY_parse_CLASS::CHAR_VAL=291;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		92
#define	YYFLAG		-32768
#define	YYNTBASE	37

#define YYTRANSLATE(x) ((unsigned)(x) <= 291 ? yytranslate[x] : 53)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     1,     4,     8,    12,    16,    20,    25,    27,    29,
    33,    35,    39,    41,    45,    47,    51,    53,    57,    61,
    65,    69,    73,    75,    77,    79,    83,    87,    90,    94,
    96,   100,   104,   108,   112,   116,   120,   122,   125,   128,
   134,   138,   141,   142
};

static const short yyrhs[] = {    -1,
    37,    38,     0,     3,    39,     7,     0,     4,    40,     7,
     0,     5,    41,     7,     0,     6,    42,     7,     0,    33,
    10,    43,     7,     0,    47,     0,    51,     0,    39,     8,
    33,     0,    33,     0,    40,     8,    33,     0,    33,     0,
    41,     8,    33,     0,    33,     0,    42,     8,    33,     0,
    33,     0,    43,    11,    43,     0,    43,    12,    43,     0,
    43,    13,    43,     0,    43,    14,    43,     0,    15,    43,
    16,     0,    44,     0,    33,     0,    34,     0,    45,    25,
    45,     0,    45,    26,    45,     0,    24,    45,     0,    15,
    45,    16,     0,    46,     0,    44,    22,    44,     0,    44,
    23,    44,     0,    44,    29,    44,     0,    44,    30,    44,
     0,    44,    31,    44,     0,    44,    32,    44,     0,    44,
     0,    48,     7,     0,    48,    50,     0,    17,    15,    45,
    16,    49,     0,    27,    37,    28,     0,    18,    49,     0,
     0,    20,    15,    45,    16,    52,    27,    37,    28,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    56,    57,    61,    62,    63,    64,    65,    68,    69,    74,
    75,    77,    78,    80,    81,    83,    84,    86,    87,    88,
    89,    90,    91,    93,    93,    96,    96,    97,    98,    99,
   102,   102,   103,   104,   105,   106,   107,   111,   111,   113,
   115,   116,   118,   118
};

static const char * const yytname[] = {   "$","error","$illegal.","INT","FLOAT",
"CHAR","DOUBLE","SEMICOLON","COMMA","END","EQUAL","PLUS","MINUS","MUL","DIV",
"LEFT","RIGHT","IF","ELSE","FOR","WHILE","DO","LESS","GREATER","NOT","AND","OR",
"CL","CR","LESSEQ","GREATEREQ","EQEQ","NOTEQ","ID","INT_VAL","FLOAT_VAL","CHAR_VAL",
"VarDec","Start","ID1","ID2","ID3","ID4","EVAL","ID5","CONDITION","COMPARE",
"EVALC","EVALIF","STATEMENTS","EVALELSE","CHECKWHILE","@1",""
};
#endif

static const short yyr1[] = {     0,
    37,    37,    38,    38,    38,    38,    38,    38,    38,    39,
    39,    40,    40,    41,    41,    42,    42,    43,    43,    43,
    43,    43,    43,    44,    44,    45,    45,    45,    45,    45,
    46,    46,    46,    46,    46,    46,    46,    47,    47,    48,
    49,    50,    52,    51
};

static const short yyr2[] = {     0,
     0,     2,     3,     3,     3,     3,     4,     1,     1,     3,
     1,     3,     1,     3,     1,     3,     1,     3,     3,     3,
     3,     3,     1,     1,     1,     3,     3,     2,     3,     1,
     3,     3,     3,     3,     3,     3,     1,     2,     2,     5,
     3,     2,     0,     8
};

static const short yydefact[] = {     1,
     0,     0,     0,     0,     0,     0,     0,     0,     2,     8,
     0,     9,    11,     0,    13,     0,    15,     0,    17,     0,
     0,     0,     0,    38,     0,    39,     3,     0,     4,     0,
     5,     0,     6,     0,     0,     0,    24,    25,    37,     0,
    30,     0,     0,     0,    23,     1,    42,    10,    12,    14,
    16,     0,    28,     0,     0,     0,     0,     0,     0,     0,
     0,     0,    43,     0,     7,     0,     0,     0,     0,     0,
    29,    31,    32,    33,    34,    35,    36,    40,    26,    27,
     0,    22,    18,    19,    20,    21,    41,     1,     0,    44,
     0,     0
};

static const short yydefgoto[] = {     1,
     9,    14,    16,    18,    20,    44,    39,    40,    41,    10,
    11,    47,    26,    12,    81
};

static const short yypact[] = {-32768,
     4,   -31,   -17,    16,    23,    74,    75,    90,-32768,-32768,
    -1,-32768,-32768,    11,-32768,    15,-32768,    51,-32768,    64,
    33,    33,    -4,-32768,    76,-32768,-32768,    58,-32768,    69,
-32768,    71,-32768,    72,    33,    33,-32768,-32768,    55,   -13,
-32768,    44,    -4,    81,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,    57,-32768,    41,    41,    41,    41,    41,    41,    76,
    33,    33,-32768,    85,-32768,    -4,    -4,    -4,    -4,    22,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
    79,-32768,    66,    66,-32768,-32768,-32768,-32768,    48,-32768,
   107,-32768
};

static const short yypgoto[] = {   -41,
-32768,-32768,-32768,-32768,-32768,    -5,   -23,   -21,-32768,-32768,
-32768,    49,-32768,-32768,-32768
};


#define	YYLAST		109


static const short yytable[] = {    45,
    42,    13,    60,    91,    70,    24,     2,     3,     4,     5,
    43,    61,    62,    52,    53,    15,    25,    27,    28,    45,
     6,    29,    30,     7,     2,     3,     4,     5,    37,    38,
    72,    73,    74,    75,    76,    77,     8,    64,     6,    79,
    80,     7,    45,    45,    45,    45,    89,    35,    17,    87,
     2,     3,     4,     5,     8,    19,    36,    31,    32,    63,
    83,    84,    85,    86,     6,    37,    38,     7,    61,    62,
    33,    34,    71,    37,    38,    90,    54,    55,    68,    69,
     8,    61,    62,    56,    57,    58,    59,    65,    21,    22,
    48,    66,    67,    68,    69,    66,    67,    68,    69,    23,
    82,    49,    46,    50,    51,    88,    92,     0,    78
};

static const short yycheck[] = {    23,
    22,    33,    16,     0,    46,     7,     3,     4,     5,     6,
    15,    25,    26,    35,    36,    33,    18,     7,     8,    43,
    17,     7,     8,    20,     3,     4,     5,     6,    33,    34,
    54,    55,    56,    57,    58,    59,    33,    43,    17,    61,
    62,    20,    66,    67,    68,    69,    88,    15,    33,    28,
     3,     4,     5,     6,    33,    33,    24,     7,     8,    16,
    66,    67,    68,    69,    17,    33,    34,    20,    25,    26,
     7,     8,    16,    33,    34,    28,    22,    23,    13,    14,
    33,    25,    26,    29,    30,    31,    32,     7,    15,    15,
    33,    11,    12,    13,    14,    11,    12,    13,    14,    10,
    16,    33,    27,    33,    33,    27,     0,    -1,    60
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 3:
#line 61 "pract5.y"
{display();;
    break;}
case 4:
#line 62 "pract5.y"
{display();;
    break;}
case 5:
#line 63 "pract5.y"
{display();;
    break;}
case 6:
#line 64 "pract5.y"
{display();;
    break;}
case 7:
#line 65 "pract5.y"
{if(!flag) 
								set(strdup(yyvsp[-3].string),yyvsp[-1].i);
								;
    break;}
case 8:
#line 68 "pract5.y"
{display();;
    break;}
case 9:
#line 69 "pract5.y"
{display();;
    break;}
case 10:
#line 74 "pract5.y"
{insert(strdup(yyvsp[0].string),strdup("int"));;
    break;}
case 11:
#line 75 "pract5.y"
{insert(strdup(yyvsp[0].string),strdup("int"));;
    break;}
case 12:
#line 77 "pract5.y"
{insert(strdup(yyvsp[0].string),strdup("float"));;
    break;}
case 13:
#line 78 "pract5.y"
{insert(strdup(yyvsp[0].string),strdup("float"));;
    break;}
case 14:
#line 80 "pract5.y"
{insert(strdup(yyvsp[0].string),strdup("char"));;
    break;}
case 15:
#line 81 "pract5.y"
{insert(strdup(yyvsp[0].string),strdup("char"));;
    break;}
case 16:
#line 83 "pract5.y"
{insert(strdup(yyvsp[0].string),strdup("double"));;
    break;}
case 17:
#line 84 "pract5.y"
{insert(strdup(yyvsp[0].string),strdup("double"));;
    break;}
case 18:
#line 86 "pract5.y"
{yyval.i = yyvsp[-2].i + yyvsp[0].i;;
    break;}
case 19:
#line 87 "pract5.y"
{yyval.i = yyvsp[-2].i - yyvsp[0].i;;
    break;}
case 20:
#line 88 "pract5.y"
{yyval.i = yyvsp[-2].i * yyvsp[0].i;;
    break;}
case 21:
#line 89 "pract5.y"
{yyval.i = yyvsp[-2].i / yyvsp[0].i;;
    break;}
case 22:
#line 90 "pract5.y"
{yyval.i = yyvsp[-1].i;;
    break;}
case 23:
#line 91 "pract5.y"
{yyval.i=yyvsp[0].i;;
    break;}
case 24:
#line 93 "pract5.y"
{variable *v1=search(yyvsp[0].string);yyval.i=v1->value;;
    break;}
case 25:
#line 93 "pract5.y"
{yyval.i=yyvsp[0].i;;
    break;}
case 26:
#line 96 "pract5.y"
{yyval.i = yyvsp[-2].i && yyvsp[0].i;flag = !yyval.i;;
    break;}
case 27:
#line 97 "pract5.y"
{yyval.i = yyvsp[-2].i || yyvsp[0].i;flag = !yyval.i;;
    break;}
case 28:
#line 98 "pract5.y"
{yyval.i = !yyvsp[0].i;flag = !yyval.i;;
    break;}
case 29:
#line 99 "pract5.y"
{yyval.i=yyvsp[-1].i;flag = !yyval.i;;
    break;}
case 30:
#line 100 "pract5.y"
{yyval.i=yyvsp[0].i;flag = !yyval.i;;
    break;}
case 31:
#line 102 "pract5.y"
{yyval.i = yyvsp[-2].i < yyvsp[0].i ? 1:0;;
    break;}
case 32:
#line 103 "pract5.y"
{yyval.i = yyvsp[-2].i > yyvsp[0].i ? 1:0;;
    break;}
case 33:
#line 104 "pract5.y"
{yyval.i = yyvsp[-2].i <= yyvsp[0].i ? 1:0;;
    break;}
case 34:
#line 105 "pract5.y"
{yyval.i = yyvsp[-2].i >= yyvsp[0].i ? 1:0;;
    break;}
case 35:
#line 106 "pract5.y"
{yyval.i = yyvsp[-2].i == yyvsp[0].i ? 1:0;;
    break;}
case 36:
#line 107 "pract5.y"
{yyval.i = yyvsp[-2].i != yyvsp[0].i ? 1:0;;
    break;}
case 37:
#line 108 "pract5.y"
{yyval.i=yyvsp[0].i;;
    break;}
case 38:
#line 111 "pract5.y"
{printf("\nElse not found.\n");;
    break;}
case 40:
#line 113 "pract5.y"
{flag = !flag;;
    break;}
case 41:
#line 115 "pract5.y"
{flag = 0;;
    break;}
case 42:
#line 116 "pract5.y"
{printf("Got else.\n"); ;
    break;}
case 43:
#line 118 "pract5.y"
{flag = 1;;
    break;}
case 44:
#line 118 "pract5.y"
{printf("Syntax is correct. Not evaluating. \n");;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 120 "pract5.y"


//Hashing function - DJB2 Algorithm
int hashCalc(unsigned char *str)
{
	unsigned long hash = 5381;
	int c;
	while (c = *str++)
    	hash = ((hash << 5) + hash) + c; 
	return hash % 1000;
}

//Insert into Hashtable
int insert(char* name, char* type)
{
	//Check for duplicates before insert
	variable* result = search(name);
	if(result == NULL)
	{
		//Allocate Memory
		variable* new = (variable*) malloc(sizeof(variable));
		strcpy(new->name,name);
		strcpy(new->type,type);
		new->next=NULL;
		//Calculate hash
		int hash = hashCalc(new->name);
		//printf("\nInsertingHash of %s is %d\n",new->name,hash);

		//Insert in Symbol Table
		if(symbolTable[hash] == NULL)
		{
			//Array position is empty, add there only
			symbolTable[hash] = new;
		}
		else
		{
			new->next = symbolTable[hash];
			symbolTable[hash] = new;
		}
		return 1;
	}
	else
	{
		//Check which kind of duplicate
		if(strcmp(result->name,name) == 0)
		{
			if(strcmp(result->type,type) == 0)
			{
				printf("Redeclaration of Variable");
				return 0;
			}	
			else
			{
				printf("Multiple Declaration of Variable");
				return 0;
			}
		}
	}
	
}

//Search Hashtable
variable* search(char* input)
{
	int hash = hashCalc(input);
	//printf("\nSearchingHash of %s is %d\n",input,hash);
	if(symbolTable[hash] != NULL)
	{
		if(symbolTable[hash]->next == NULL)
		{
			//Only one entry here
			if(!strcmp(symbolTable[hash]->name,input)) return symbolTable[hash];
		}
		else
		{
			//Chained entry - Linear Search required
			variable* temp = symbolTable[hash];
			while(temp != NULL)
			{
				if(strcmp(temp->name,input) == 0)
					return temp;
				else
					temp = temp->next;
			}
		}
	}
	return NULL;
}


//Display HashTable
void display()
{
	printf("\n%10s %10s %10s\n","Name","Type","Value");
	int i = 0;
	for(i = 0;i < 1000;i++)
	{
		//Skip if Empty entry
		if(symbolTable[i] == NULL)
		{
			continue;
		}
		//Chained Entries
		else if(symbolTable[i]->next != NULL)
		{
			variable* temp = symbolTable[i];
			while(temp != NULL)
			{
				printf("%10s %10s %10d\n",temp->name,temp->type,temp->value);
				temp = temp->next;
			}
		}
		//Single Entry
		else
		{
			printf("%10s %10s %10d\n",symbolTable[i]->name,symbolTable[i]->type,symbolTable[i]->value);
		}
	}
}

void freeTable()
{
	int i = 0;
	for(i = 0;i < 1000;i++)
	{
		//Skip if Empty entry
		if(symbolTable[i] == NULL)
		{
			continue;
		}
		//Chained Entries
		else if(symbolTable[i]->next != NULL)
		{
			variable* temp = symbolTable[i];
			variable* freeVar;
			while(temp != NULL)
			{
				freeVar = temp;
				temp = temp->next;
				free(freeVar);
			}
		}
		//Single Entry
		else
		{
			free(symbolTable[i]);
		}
	}
}

void init()
{
	int i = 0;
	for(i = 0;i < 1000;i++)
	{
		symbolTable[i] = NULL;
	}
}

//Error Handling
void yyerror(const char *str)
{
	printf("\nSyntax Error - Freeing Symbol Table\n");
	freeTable();
}

//Wrap
int yywrap()
{
	return 1;
}

void main()
{
    init();	
	yyparse();
}

void set(char *name,int value){
	variable *v1 = search(name);
	v1->value = value;
	printf("Value of %s = %d\n",v1->name,v1->value);
}
